/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Organisation } from "./Organisation";
import { OrganisationCountArgs } from "./OrganisationCountArgs";
import { OrganisationFindManyArgs } from "./OrganisationFindManyArgs";
import { OrganisationFindUniqueArgs } from "./OrganisationFindUniqueArgs";
import { CreateOrganisationArgs } from "./CreateOrganisationArgs";
import { UpdateOrganisationArgs } from "./UpdateOrganisationArgs";
import { DeleteOrganisationArgs } from "./DeleteOrganisationArgs";
import { UserFindManyArgs } from "../../user/base/UserFindManyArgs";
import { User } from "../../user/base/User";
import { OrganisationService } from "../organisation.service";
@graphql.Resolver(() => Organisation)
export class OrganisationResolverBase {
  constructor(protected readonly service: OrganisationService) {}

  async _organisationsMeta(
    @graphql.Args() args: OrganisationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Organisation])
  async organisations(
    @graphql.Args() args: OrganisationFindManyArgs
  ): Promise<Organisation[]> {
    return this.service.organisations(args);
  }

  @graphql.Query(() => Organisation, { nullable: true })
  async organisation(
    @graphql.Args() args: OrganisationFindUniqueArgs
  ): Promise<Organisation | null> {
    const result = await this.service.organisation(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Organisation)
  async createOrganisation(
    @graphql.Args() args: CreateOrganisationArgs
  ): Promise<Organisation> {
    return await this.service.createOrganisation({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Organisation)
  async updateOrganisation(
    @graphql.Args() args: UpdateOrganisationArgs
  ): Promise<Organisation | null> {
    try {
      return await this.service.updateOrganisation({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Organisation)
  async deleteOrganisation(
    @graphql.Args() args: DeleteOrganisationArgs
  ): Promise<Organisation | null> {
    try {
      return await this.service.deleteOrganisation(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [User], { name: "users" })
  async findUsers(
    @graphql.Parent() parent: Organisation,
    @graphql.Args() args: UserFindManyArgs
  ): Promise<User[]> {
    const results = await this.service.findUsers(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
