/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { OrganisationService } from "../organisation.service";
import { OrganisationCreateInput } from "./OrganisationCreateInput";
import { Organisation } from "./Organisation";
import { OrganisationFindManyArgs } from "./OrganisationFindManyArgs";
import { OrganisationWhereUniqueInput } from "./OrganisationWhereUniqueInput";
import { OrganisationUpdateInput } from "./OrganisationUpdateInput";
import { UserFindManyArgs } from "../../user/base/UserFindManyArgs";
import { User } from "../../user/base/User";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

export class OrganisationControllerBase {
  constructor(protected readonly service: OrganisationService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Organisation })
  async createOrganisation(
    @common.Body() data: OrganisationCreateInput
  ): Promise<Organisation> {
    return await this.service.createOrganisation({
      data: data,
      select: {
        createdAt: true,
        id: true,
        licenseStatus: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Organisation] })
  @ApiNestedQuery(OrganisationFindManyArgs)
  async organisations(@common.Req() request: Request): Promise<Organisation[]> {
    const args = plainToClass(OrganisationFindManyArgs, request.query);
    return this.service.organisations({
      ...args,
      select: {
        createdAt: true,
        id: true,
        licenseStatus: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Organisation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async organisation(
    @common.Param() params: OrganisationWhereUniqueInput
  ): Promise<Organisation | null> {
    const result = await this.service.organisation({
      where: params,
      select: {
        createdAt: true,
        id: true,
        licenseStatus: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Organisation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateOrganisation(
    @common.Param() params: OrganisationWhereUniqueInput,
    @common.Body() data: OrganisationUpdateInput
  ): Promise<Organisation | null> {
    try {
      return await this.service.updateOrganisation({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          licenseStatus: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Organisation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteOrganisation(
    @common.Param() params: OrganisationWhereUniqueInput
  ): Promise<Organisation | null> {
    try {
      return await this.service.deleteOrganisation({
        where: params,
        select: {
          createdAt: true,
          id: true,
          licenseStatus: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/users")
  @ApiNestedQuery(UserFindManyArgs)
  async findUsers(
    @common.Req() request: Request,
    @common.Param() params: OrganisationWhereUniqueInput
  ): Promise<User[]> {
    const query = plainToClass(UserFindManyArgs, request.query);
    const results = await this.service.findUsers(params.id, {
      ...query,
      select: {
        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        lastName: true,

        organisation: {
          select: {
            id: true,
          },
        },

        password: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/users")
  async connectUsers(
    @common.Param() params: OrganisationWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      users: {
        connect: body,
      },
    };
    await this.service.updateOrganisation({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/users")
  async updateUsers(
    @common.Param() params: OrganisationWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      users: {
        set: body,
      },
    };
    await this.service.updateOrganisation({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/users")
  async disconnectUsers(
    @common.Param() params: OrganisationWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      users: {
        disconnect: body,
      },
    };
    await this.service.updateOrganisation({
      where: params,
      data,
      select: { id: true },
    });
  }
}
